version: "3.9"
services:
  parameter_server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    command: ["12345"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
    cpuset: "2"
    ports:
      - "12345:12345"
    volumes:
      - ./results/server_logs:/app/elastic_center
    networks:
      train_net:
        ipv4_address: 172.31.0.10
    environment:
      - SERVER_PORT=12345

  worker1:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.worker
    command: ["1", "172.31.0.10", "12345"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
    cpuset: "0"
    depends_on:
      - parameter_server
    volumes:
      - ./results/worker1_results:/app/worker_1_final
    networks:
      train_net:
        ipv4_address: 172.31.0.11
    restart: on-failure

  worker2:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.worker
    command: ["2", "172.31.0.10", "12345"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
    cpuset: "1"
    depends_on:
      - parameter_server
    volumes:
      - ./results/worker2_results:/app/worker_2_final
    networks:
      train_net:
        ipv4_address: 172.31.0.12
    restart: on-failure

networks:
  train_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16